plugins {
    id 'java'
    id 'checkstyle'
}

group = 'hei'
version = '1.0-SNAPSHOT'

checkstyle {
    toolVersion = '10.17.0'
    // --- ICI ---
    configFile = file('src/main/resources/checkstyle.xml')
    // -----------
    showViolations = true
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}